wafflestudio/areyouhere-server

- src/main/java/com/waruru/areyouhere/common/config/UtilityConfig.java
- src/main/java/com/waruru/areyouhere/common/utils/AlphanumericIdGenerator.java
- src/main/java/com/waruru/areyouhere/common/utils/RandomIdentifierGenerator.java
- 구분을 위한 랜덤한 식별자를 생성하는 코드 입니다. 
- 사용성을 고려하여 /common/utils 패키지에 코드를 위치 시켰습니다.
- 추후 로직 변경 가능성을 고려하여 인터페이스화하여 빈 주입하였습니다.
- Random을 이용하여 a-z0-9 사이에서 4개를 선별합니다.
- [v] 새로운 기능 추가
> Feat/utils-random-identifier-generator: 랜덤 식별자 생성기 구현

- src/main/java/com/waruru/areyouhere/attendee/domain/entity/Attendee.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/AttendeeRepository.java
- src/main/java/com/waruru/areyouhere/course/advice/CourseExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/course/controller/CourseController.java
- src/main/java/com/waruru/areyouhere/course/domain/entity/Course.java
- src/main/java/com/waruru/areyouhere/course/domain/repository/CourseRepository.java
- src/main/java/com/waruru/areyouhere/course/dto/request/CourseCreationRequest.java
- src/main/java/com/waruru/areyouhere/course/dto/request/CourseUpdateRequest.java
- src/main/java/com/waruru/areyouhere/course/exception/CourseException.java
- src/main/java/com/waruru/areyouhere/course/exception/CourseNotFoundException.java
- src/main/java/com/waruru/areyouhere/course/exception/ManagerNotFoundException.java
- src/main/java/com/waruru/areyouhere/course/exception/UnauthorizedManagerException.java
- src/main/java/com/waruru/areyouhere/course/service/CourseService.java
- src/main/java/com/waruru/areyouhere/course/service/CourseServiceImpl.java
> Feat/course-crud: course 서비스에 대한 CRUD 구현

- build.gradle
- src/main/java/com/waruru/areyouhere/attendance/domain/entity/Attendance.java
- src/main/java/com/waruru/areyouhere/attendance/domain/repository/AttendanceRepository.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceService.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendance/service/dto/AttendanceCount.java
- src/main/java/com/waruru/areyouhere/common/config/RedisConfig.java
- src/main/java/com/waruru/areyouhere/common/utils/HttpStatusResponseEntity.java
- src/main/java/com/waruru/areyouhere/manager/advice/ManagerExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/session/advice/SessionExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/session/controller/AuthCodeController.java
- src/main/java/com/waruru/areyouhere/session/controller/DashBoardController.java
- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/AuthCode.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/Session.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/AuthCodeRedisRepository.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- src/main/java/com/waruru/areyouhere/session/dto/CurrentSessionResponseDto.java
- src/main/java/com/waruru/areyouhere/session/dto/RecentFiveSessionResponseDto.java
- src/main/java/com/waruru/areyouhere/session/exception/CourseIdNotFoundException.java
- src/main/java/com/waruru/areyouhere/session/exception/CurrentSessionNotFoundException.java
- src/main/java/com/waruru/areyouhere/session/exception/SessionIdNotFoundException.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeService.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/SessionService.java
- src/main/java/com/waruru/areyouhere/session/service/SessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/dto/CurrentSessionDto.java
- src/main/resources/application-db.yml
- Session DashBoard에 필요한 로직 구현
- Session DashBoard 구현
- session 출석자 결석자 조회 구현
> Feat/session: Session DashBoard 구현

- .github/workflows/deploy.yml
- Dockerfile
- 메인 병합시 자동으로 ECR 레포에 도커 이미지 푸시
- 메인 병합시 자동으로 ECR 레포에 도커 이미지 푸시
> Feat/ci-cd-setup: 메인 병합시 자동으로 ECR 레포에 도커 이미지 푸시

- src/main/java/com/waruru/areyouhere/attendance/advice/AttendanceExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/attendance/domain/entity/Attendance.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceService.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/AttendeeRepository.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeService.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/controller/AuthCodeController.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- authcode가 deactivate가 되면 그에 따라 결석자들이 일괄적으로 DB에 반영
- attendance에서 course_id와 session_id를 받아 결석자들을 일괄적으로 DB에 반영
> Feat/AuthCode 출석코드 Deactivation 후에 결석자 처리

- .github/workflows/deploy.yml
- Dockerfile
- Fix/ci-cd-setup: CI-CD 오류 수정
> Fix/ci-cd-setup: CI-CD 오류 수정

- .github/workflows/deploy.yml
-fix: typo-error-in-depoly.yml
- 
- [ㅍ] 버그 수정
> fix: typo-error-in-depoly.yml

- .github/workflows/deploy.yaml
> fix: whitespace 2

- build.gradle
- src/main/resources/application-prod.yaml
- Feat/actuator: probe를 위해 spring actuator endpoint 설정
-
> Feat/actuator: probe를 위해 spring actuator endpoint 설정

- Dockerfile
- build.gradle
- CD에서 `Error: Unable to access jarfile /app.jar` 나는 것을 해결합니다.
- `build.gradle`에서 JAR 파일의 이름을 바꾸고
- `Dockerfile`에서 JAR 파일의 경로를 알맞게 설정합니다
> 빌드된 JAR 파일 경로 수정

- src/main/resources/application-prod.yaml
- 의존성 문제 해결을 위해 redis port number 추가
-
> feat: add redis port number

- .github/workflows/deploy.yaml
- faet: set credentials 순서 변경
-
> faet: set credentials 순서 변경

- src/main/java/com/waruru/areyouhere/attendance/domain/entity/Attendance.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/AttendeeRepository.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/dto/ClassAttendeeInfo.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/dto/SessionAttendeeInfo.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendee/service/dto/ClassAttendees.java
- src/main/java/com/waruru/areyouhere/attendee/service/dto/SessionAttendees.java
- src/main/java/com/waruru/areyouhere/manager/controller/ManagerController.java
- src/main/java/com/waruru/areyouhere/manager/dto/response/ManagerDto.java
- src/main/java/com/waruru/areyouhere/session/advice/SessionExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/AuthCode.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/Session.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/AuthCodeRedisRepository.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/dto/SessionInfo.java
- src/main/java/com/waruru/areyouhere/session/exception/AuthCodeNotFoundException.java
- src/main/java/com/waruru/areyouhere/session/exception/StudentNameNotFoundException.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeService.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/SessionService.java
- src/main/java/com/waruru/areyouhere/session/service/SessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/dto/SessionAttendanceInfo.java
- 상세 세션 조회, AuthCode deactivation, 참가자 상세 페이지 구현
-
> Feat/attendance: 상세 세션 조회, AuthCode deactivation, 참가자 상세 페이지 구현

- src/main/resources/application.yaml
> fix: yaml-to-prod 수정

- src/main/java/com/waruru/areyouhere/common/config/WebSecurityConfig.java
- 빈형식으로 websecurity-config 추가
- 
- [v] 새로운 기능 추가
> feat/add-websecurity-config: 빈형식으로 websecurity-config 추가

- src/main/resources/application-prod.yaml
> feat: ddl-auto-create 원활한 개발을 위해 옵션추가

- src/main/resources/application-prod.yaml
- feat: create-drop-mode로 변경
-
> feat: create-drop-mode

- src/main/resources/application-prod.yaml
> feat: generate-ddl

- src/main/java/com/waruru/areyouhere/attendance/domain/entity/Attendance.java
- src/main/java/com/waruru/areyouhere/attendee/domain/repository/AttendeeRepository.java
- src/main/java/com/waruru/areyouhere/session/controller/AuthCodeController.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/AuthCode.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/Session.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeService.java
- src/main/java/com/waruru/areyouhere/session/service/AuthCodeServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/SessionService.java
- src/main/java/com/waruru/areyouhere/session/service/SessionServiceImpl.java
- current Session이 auth code를 만들지 않았더라도 id를 정상적으로 반환하도록 수정
- session이 생성 시점이 아니라 출석을 체크하기 시작한 시간을 표시하도록 수정
-
> Fix/bug: currentSession 및 previous session 조회에서 날짜 반환 로직 수정

- src/main/java/com/waruru/areyouhere/attendance/controller/AuthCodeController.java
- src/main/java/com/waruru/areyouhere/attendance/domain/entity/CurrentSessionAttendanceInfo.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRedisServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/advice/SessionExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/session/controller/DashBoardController.java
- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/AuthCodeRedisRepository.java
- src/main/java/com/waruru/areyouhere/session/service/SessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/query/SessionQueryServiceImpl.java
> Refactor/Session: Service layer 함수 분리

- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRedisServiceImpl.java
- src/main/java/com/waruru/areyouhere/common/config/WebConfig.java
- src/main/java/com/waruru/areyouhere/session/service/query/SessionQueryServiceImpl.java
- src/main/resources/application-dev.yaml
- src/main/resources/application-temp.yaml
- 하드 코딩된 환경 변수 설정.
- 
- [] 코드 리팩토링
> feat: 환경변수 환경 별 별도 설정

- .github/workflows/develop.yaml
- src/main/resources/application-dev.yaml
- src/main/resources/application.yaml
> Feat/develop 환경 배포 자동화

- src/main/resources/application-dev.yaml
> feat: develop 환경 https 적용

- .github/workflows/release.yaml
- src/main/java/com/waruru/areyouhere/attendee/service/command/AttendeeCommandServiceImpl.java
- Attendee 변경에서 이름 변경도 가능하도록 수정
> Feat/Attendee 참가자 변경에서 이름 변경도 가능하도록 수정

- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/java/com/waruru/areyouhere/session/domain/entity/Session.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- src/main/java/com/waruru/areyouhere/session/dto/request/UpdateSessionsRequestDto.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/dto/UpdateSession.java
> Feat/Session 세션 일괄 수정 구현 

- src/main/java/com/waruru/areyouhere/attendance/advice/AttendanceExceptionAdvice.java
- src/main/java/com/waruru/areyouhere/attendance/controller/AttendanceController.java
- src/main/java/com/waruru/areyouhere/attendance/controller/AuthCodeController.java
- src/main/java/com/waruru/areyouhere/attendance/dto/response/CurrentAttendanceCountResponseDto.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRDBService.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRDBServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRedisService.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceRedisServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceService.java
- src/main/java/com/waruru/areyouhere/attendance/service/AttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendance/service/dto/CurrentSessionAttendCount.java
- src/main/java/com/waruru/areyouhere/attendee/controller/AttendeeController.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendee/service/query/AttendeeQueryService.java
- src/main/java/com/waruru/areyouhere/course/controller/CourseController.java
- src/main/java/com/waruru/areyouhere/course/service/CourseService.java
- src/main/java/com/waruru/areyouhere/course/service/CourseServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/AuthCodeRedisRepository.java
- src/main/java/com/waruru/areyouhere/session/service/SessionService.java
- src/main/java/com/waruru/areyouhere/session/service/SessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/query/SessionQueryService.java
- src/main/java/com/waruru/areyouhere/session/service/query/SessionQueryServiceImpl.java
- 명확하지 않았던 출석 검증과 출석 삽입 시점 분리
- Redis에 삽입 시점이 불명확했던 문제점 해결
> Feat/attendance 출석 검증과 출석 삽입 시점 분리

- src/main/java/com/waruru/areyouhere/AreYouHereApplication.java
- src/main/java/com/waruru/areyouhere/active/ActiveSessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeService.java
- src/main/java/com/waruru/areyouhere/attendee/service/AttendeeServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
> Fix/Timezone: change default timezone to Asia/Seoul

- src/main/java/com/waruru/areyouhere/active/ActiveSessionController.java
- src/main/java/com/waruru/areyouhere/active/service/ActiveSessionService.java
- src/main/java/com/waruru/areyouhere/active/service/ActiveSessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/course/controller/CourseController.java
- src/main/java/com/waruru/areyouhere/manager/controller/ManagerController.java
- src/main/java/com/waruru/areyouhere/manager/domain/entity/Manager.java
- src/main/java/com/waruru/areyouhere/manager/service/ManagerService.java
- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/java/com/waruru/areyouhere/session/domain/repository/SessionRepository.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
- src/main/java/com/waruru/areyouhere/session/service/query/SessionQueryServiceImpl.java
> refactor: 메소드명 일관성 있게 변경

- src/main/java/com/waruru/areyouhere/manager/controller/ManagerController.java
- src/main/java/com/waruru/areyouhere/manager/domain/repository/ManagerRepository.java
- src/main/java/com/waruru/areyouhere/manager/service/ManagerService.java
- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
> Feat/Manager Manager 삭제

- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
> Feat/Session: 활성화되지 않은 세션 삭제 API

- .github/workflows/develop.yaml
- .github/workflows/release.yaml
- build.gradle
- src/main/java/com/waruru/areyouhere/active/service/ActiveAttendanceServiceImpl.java
- src/main/java/com/waruru/areyouhere/common/config/EmailConfig.java
- src/main/java/com/waruru/areyouhere/common/config/RedisConfig.java
- src/main/java/com/waruru/areyouhere/common/config/UtilityConfig.java
- src/main/java/com/waruru/areyouhere/common/utils/random/AlphanumericIdGenerator.java
- src/main/java/com/waruru/areyouhere/common/utils/random/RandomIdentifierGenerator.java
- src/main/java/com/waruru/areyouhere/email/domain/MessageHolder.java
- src/main/java/com/waruru/areyouhere/email/domain/MessageTemplate.java
- src/main/java/com/waruru/areyouhere/email/service/EmailService.java
- src/main/java/com/waruru/areyouhere/email/service/JavaEmailServiceImpl.java
- src/main/java/com/waruru/areyouhere/manager/controller/ManagerController.java
- src/main/java/com/waruru/areyouhere/manager/domain/repository/VerifyCodeRepository.java
- src/main/java/com/waruru/areyouhere/manager/dto/request/ResetPasswordRequestDto.java
- src/main/java/com/waruru/areyouhere/manager/dto/request/SignUpRequestDto.java
- src/main/java/com/waruru/areyouhere/manager/dto/request/VerifyEmailRequestDto.java
- src/main/java/com/waruru/areyouhere/manager/service/ManagerService.java
- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
- src/main/java/com/waruru/areyouhere/session/controller/SessionController.java
- src/main/resources/application-dev.yaml
- src/main/resources/application-local.yaml
- src/main/resources/application-release.yaml
- 회원가입, 비밀번호 변경에 사용될 이메일 인증 서비스 구현
- 이메일 인증 서비스 구현
- 회원가입, 비밀번호 초기화 시 이메일 인증을 통하도록 변
> Feat/email 이메일 인증 서비스

- .github/workflows/develop.yaml
- .github/workflows/release.yaml
- build.gradle
- src/main/java/com/waruru/areyouhere/AreYouHereApplication.java
- src/main/java/com/waruru/areyouhere/common/annotation/SlackNotification.java
- src/main/java/com/waruru/areyouhere/common/config/SlackAspect.java
- src/main/java/com/waruru/areyouhere/common/error/ErrorResponse.java
- src/main/java/com/waruru/areyouhere/common/error/GlobalExceptionHandler.java
- src/main/java/com/waruru/areyouhere/common/utils/RequestInfo.java
- src/main/resources/application-dev.yaml
- src/main/resources/application-prod.yaml
- 서버 에러 메시지가 슬랙에 전송. 모니터링 기능.
- 슬랙 API 연결
- 전송 기능 추가
- github secret 추가
> Feat/Log-Error 슬랙에 에러메시지 연동

- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
프론트엔드 구현 전까지 이메일 인증 기능 비활성화
- 프론트단 API 연결 전까지 이메일 인증을 비활성화 합니다. 
- 아직 API 연결이 안된 관계로 이메일 인증 버튼이 없지만 API 상으로는 이메일 인증이 완료가 되지 않으면 회원가입이 되지 않습니다.
- 즉 회원가입이 불가능한 관계로 잠시 비활성화합니다.
> Hotfix/signup: 이메일 인증 비활성화

- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
- 이메일 기능 복구
- 프론트와 진척도를 맞추기 위해 제거했던 이메일 기능 복구
> fix: 이메일 기능 원복

- src/main/java/com/waruru/areyouhere/active/service/ActiveSessionServiceImpl.java
- src/main/java/com/waruru/areyouhere/auth/interceptor/LoginInterceptor.java
- src/main/java/com/waruru/areyouhere/auth/session/SessionManager.java
- src/main/java/com/waruru/areyouhere/common/error/GlobalExceptionHandler.java
- src/main/java/com/waruru/areyouhere/course/domain/repository/CourseRepository.java
- src/main/java/com/waruru/areyouhere/course/service/CourseServiceImpl.java
- src/main/java/com/waruru/areyouhere/email/domain/MessageTemplate.java
- src/main/java/com/waruru/areyouhere/manager/service/SessionManagerService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandService.java
- src/main/java/com/waruru/areyouhere/session/service/command/SessionCommandServiceImpl.java
-API에서 일어나는 마이너한 에러들을 수정
- auth 경로 변경 반영
- 404 에러 Global Handling (Slack에 알림 안 가도록 수정)
- AuthCode 생성일 변경
> Fix/Api-Error: Session Date 수정, 404 오류 Global Handling, API 경로 수정
